### ISSUE TITLE
mcpcpc website seems to be refusing connections

### ISSUE THREAD

**Issue by NotOles** [mcpcpc/kirc#106]
Hey!

A few days ago I was enjoying reading some pages on mcpcpc.com! Thanks! :)

But, right now, and during the past couple of days, 

https://mcpcpc.com/kirc/install.html

https://mcpcpc.com/kirc/howto.html

https://mcpcpc.com/kirc/faq.html

and 

https://mcpcpc.com/2021/02/12/netcat-irc-client.html

won't load. Chrome says: ERR_CONNECTION_REFUSED.

Tried coming from a different IP but no joy there. Is the site going to come back?

Best wishes and kindest regards,

Tom

**Comment by mcpcpc** [comment]
Hi Tom,

Sorry for the interruption!  I am currently in the process of migrating my hosting (and also splitting my personal domain, mcpcpc.com, from kirc development). For the interim, you can can still access all of the kirc pages at the following url:

https://mcpcpc.github.io/kirc

All blog content is now accessible via my gemini site:

gemini://mcpcpc.com

**Comment by NotOles** [comment]
Great! Now I again can see all those excellent pages! Thank you very much!
