### ISSUE TITLE
Command suggestor

### ISSUE THREAD

**Issue by cfferry** [mcpcpc/kirc#109]
Dear Michael,

I'm happy to see your project growing! I certainly applaud your ongoing work.

I was thinking that perhaps you could add a command suggester? what about suggesting commands when pressing the tab key?

I hope you're having a great weekend!

**Comment by mcpcpc** [comment]
Hi,

Thanks you for your kind words. Regarding the command suggester, I think it's worth consideration.  The text editor functionality of kirc has grown quite significantly from what I originally envisioned and, at this point, feature adoption should only be considered if absolutely necessary for usability.  If the objective is to reduce keystrokes, then I would prefer to use command aliases, which expands upon the existing functionality.  At the same time, if there are too many command aliases, then it might be cumbersome to remember all of them.  This might suggest tab-completion + command suggester might be the way to go, replacing the existing alias structure. Although, this would be at the cost of added complexity.

I will probably contemplate this one for a bit before making any decisions =P.

**Comment by mcpcpc** [comment]
Finally getting around to this!  I investigated a few different options for command suggestors.  Given the relative availability of the command alias documentation (i.e. the README, kirc.io, and the man page) and the fact that the default command aliases really haven't really been expanded in over a year, I would like to refrain from adding a command suggestor at this time.  

I think we can close the issue for now. Of course, we can always re-open this one if the situation changes down the road.
