### ISSUE TITLE
Channel joins occur before additional command is finished executing

### ISSUE THREAD

**Issue by bharris6** [mcpcpc/kirc#112]
I was trying to use the extra command flag to log in as my registered user so that my unaffiliated cloak takes effect.  The channel join ends up occurring prior to the IDENTIFY command completing, which means the cloak is not set up "in time":

`kirc -c kirc -n mynick2 -x "PRIVMSG NickServ :IDENTIFY myuser mypassword"`

Is there a way to delay the channel joins until the extra command is complete, so that the IDENTIFY command has time to complete?  Perhaps a wait/delay that can be specified somewhere?  

Note: using the SASL PLAIN authentication as shown in the documentation correctly logs the user in and has the cloak set up before any channels are joined.  However, this issue is sort of a side case where a user either doesn't want to or can't create an authentication token.  

Working SASL PLAIN command:

    python -c 'import base64; print(base64.encodebytes(b"myuser\x00myuser\x00mypassword"))'
    kirc -c kirc -n mynick2 -a <base64-output-of-above>

**Comment by mcpcpc** [comment]
Thanks for submitting this and the pleasant chat on IRC. Per our conversation, I think we can close this one out by updating the support documentation (with adding specific examples for -x argument usage).  

-mcpcpc

**Comment by bharris6** [comment]
That works for me, especially since this was kind of a corner case issue anyways -- I mean, I'd be surprised if someone were using `kirc` but didn't have a tool available for doing the base64 token creation!

**Comment by mcpcpc** [comment]
Added a section in the supplied documentation: https://github.com/mcpcpc/kirc/commit/bd5280a81726dbae1028e893cd8cb87b102cedb7
