### ISSUE TITLE
geeknode commands support

### ISSUE THREAD

**Issue by caywin25** [mcpcpc/kirc#120]
Hello,

Thank you for you work, kirc is beautiful

All days, I am on geeknode server and main commands are done via /msg and not /nickserv.
If I try to do /msg, the command is not found. I think that this one is not implemented.

Would it be possible to add this command please?
More information here: https://geeknode.org/

Thanks a lot

**Comment by mcpcpc** [comment]
Thank you for your kind words =).

 Regarding the `/msg` command, as far as I am aware, is not standard per the IRC protocol  (https://datatracker.ietf.org/doc/html/rfc1459).  I would speculate the `/msg` command is actually an alias for `/privmsg`. This is common in many other clients, such as mIRC.  
For example, going through the (translated) main page, the first example of using `/msg` is this:

```
/msg C nick register mot_de_passe adresse_mail
```

In *kirc*, the same command would be specified as follows:

```
@C nick register mot_de_passe adresse_mail
```

The `@` is telling the server we would like to send a `/msg` or `/privmsg` to `C`.

Hope this information helps.

- mcpcpc

**Comment by caywin25** [comment]
Oh yes it's perfect.
Thank you very much.

I close this issue.
Regards
