### ISSUE TITLE
Piping to tee unusable

### ISSUE THREAD

**Issue by zzaba** [mcpcpc/kirc#121]
I tried piping output of `kirc` to `tee` as a simple way of keeping logs, but it only displayed output on terminal once I hit Control-C. I tried piping `iwctl` to `tee` as well and it behaved as expected, so the issue is not with `tee`. I checked with `alacritty` and `st`, both display `?>` then `#>` then the log once I hit Control-C. `Alacritty` blinks the line occasionally. Also, `cat`ing the log results in my command line being populated with ` ;1R;2R;4R;95R;`... I tested 0.2.9, provided by my distro(void), and upstream that I compiled by cloning and running `make`.

The commands I issued: `kirc -c <chan> -n <nick> -k <pass> | tee irc.log` and `cat irc.log` and `iwctl | tee iwctl.log`

**Comment by mcpcpc** [comment]
Tee will not work and has not worked (see https://github.com/mcpcpc/kirc/issues/2 and https://github.com/mcpcpc/kirc/issues/73 for some background). Did you try the `-o` switch for generating a log file? For example:

```shell
$ kirc -o output.log -n mcpcpc
```
