### ISSUE TITLE
Multi-line paste?

### ISSUE THREAD

**Issue by for-coursera** [mcpcpc/kirc#142]
if I try to paste a few lines of text, kirc only sends the first line, and the rest ones cause garbage on the screen.

Is it just me, or it's a known limitation?

**Comment by stefan11111** [comment]
@for-coursera 
Could you paste the lines you were trying to send here, in this issue, too?

I regularly paste multiple lines, with no issue

**Comment by for-coursera** [comment]
@stefan11111, 

Good point! it's not the lines themselves but tmux is the culprit, it seems. When running kirc outside tmux, everything's OK.

Still, sorta strange...

**Comment by stefan11111** [comment]
@for coursera

I just tried pasting multiple lines in kirc, running in tmux.
I had no issue with it.
