### ISSUE TITLE
kirc needs --help to show its help!

### ISSUE THREAD

**Issue by antdude** [mcpcpc/kirc#16]
As a newbie, I had no idea how to start until I saw the help in https://github.com/mcpcpc/kirc web page. :/

**Comment by mcpcpc** [comment]
Thank you for creating an issue for this!  I have pushed a new `-h` argument as part of https://github.com/mcpcpc/kirc/commit/9f769eac6136707489c0d2e4a743491a74b48fc1 to print basic usage information.
