### ISSUE TITLE
Notice -- You need to identify via SASL to use this server

### ISSUE THREAD

**Issue by Fastidious** [mcpcpc/kirc#21]
**Describe the bug**
When trying to connect to default server, I get:

`Notice -- You need to identify via SASL to use this server`

The connection closes right after.

**To Reproduce**
Just try running the program, like so:
`kirc -n SomeNick`

**Expected behavior**
It would connect to the IRC server.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 
 - Version [e.g. 22]: 20.X

**Comment by mcpcpc** [comment]
i encountered this before, but when using `sic`.  Will take a look.  Might be a day or two before i can confirm this issue as I am currently traveling ^^.

**Comment by mcpcpc** [comment]
@Fastidious : just a quick thought. can you try specifying a server and see if it works?  (e.g. `kornbluth.freenode.net`).

**Comment by Fastidious** [comment]
@mcpcpc same happens when passing `-s kornbluth.freenode.net`.

**Comment by mcpcpc** [comment]
Might be related to this issue: https://github.com/StackStorm-Exchange/stackstorm-irc/issues/1

i’m assuming you are operating behind one of th blacklisted IPs.  implementation doesn't look too bad.

**Comment by Fastidious** [comment]
@mcpcpc yes, Freenode's NickServ authentication is required for machines running on big cloud providers. That's it.

**Comment by mcpcpc** [comment]
Created a branch to test SASL PLAIN support: https://github.com/mcpcpc/kirc/blob/sasl-support/kirc.c which can be used with the following syntax:

```shell
kirc -n <nick> -a <token>
```

This implimentation still requires that the user know their authentication `token`, which can be generated a number of ways. In python, one could use the following line:

```shell
python -c 'import base64; print(base64.encodebytes(b"nick\x00nick\x00password"))'
```

For example, lets assume an authentication identity of `jilles` and password `sesame`:

```shell
$ python -c 'import base64; print(base64.encodebytes(b"jilles\x00jilles\x00sesame"))'
b 'amlsbGVzAGppbGxlcwBzZXNhbWU=\n'
$ kirc -n jilles -a amlsbGVzAGppbGxlcwBzZXNhbWU
```

**Comment by Fastidious** [comment]
@mcpcpc, as we briefly chatted on #kirc, it worked. I have to use:
```
python -c 'import base64; print(base64.standard_b64encode(b"nick\x00nick\x00password"))'
```
Instead, as I am on python 2 still.
