### ISSUE TITLE
Support for arrows keys, GNU Readline hotkeys?

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#24]
To start with, `kirc` definitely looks minimal, self-sufficient and just nice 👍 

However, arrows hotkeys doesn't seem to be supported? Also, adding support for [GNU Readline](https://en.wikipedia.org/wiki/GNU_Readline) would be nice, too (keys like `Ctrl-a` to go to the beginning of the line, `Ctrl-e` to go to the end of the line, etc).

**Comment by mcpcpc** [comment]
i’ want this so badly as well!  unfortunately, i don't see this panning out for a few reasons:
1. GNU `readline()` is not POSIX compliant (as far as i am aware) and would make the program less portable if i were to adopt it. 
2. to capture and manipulate stdin would require writing a custom text editor (e.g. switch from canonical mode to raw), which is scope that i am not looking to take on at this time. 


i will leave this open for a few days, see if anyone else knows something i don’t (which is very likely) or has other suggestions.

**Comment by vainiovano** [comment]
Something like [linenoise](https://github.com/antirez/linenoise) could be used instead of GNU readline for smaller size

**Comment by mcpcpc** [comment]
> Something like [linenoise](https://github.com/antirez/linenoise) could be used instead of GNU readline for smaller size

seems like a viable option. will give it a shot when i have some bandwidth.

**Comment by mcpcpc** [comment]
After reviewing various options, i feel that out best option would be to write a custom text/line editor. I think this would best align with the KISS principal, ensuring a minimal set of maintainable functions.  

However, for the same reasons, i still think this is a no-go.  This just isn’t scope that I am prepared take on at this time.  If alternative solutions are proposed, I think we can revisit this issue in the future.
