### ISSUE TITLE
Support for nick completion?

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#25]
Adding support for nick completion would be great :) (Pressing `Tab` to complete a nickname from the current channel, adding `:` after it).

**Comment by mcpcpc** [comment]
I spent the past few days evaluating various options for handling custom key bindings.  I believe TAB completion poses the same challenge as https://github.com/mcpcpc/kirc/issues/24 and a custom text editor would need to be created or adopted from a different project (e.g. linenoise)  For those reasons, I believe this is a non-starter.  

Not saying that i would never consider this again in the future.  This just isn’t scope that I am prepared take on at this time though.
