### ISSUE TITLE
If a function does not take any parameters then declare it as foo(void)

### ISSUE THREAD

**Issue by vu3rdd** [mcpcpc/kirc#26]
In https://github.com/mcpcpc/kirc/blob/4088efa0fff67fe679e07a1c1ed3e10d525feea9/kirc.c#L83 the function `connection_initialize` is declared as:
```
static int connection_initialize();
```
In ANSI C, if a function does not take any parameters, you need to include `void` as in `static int connection_initialize(void)`. Otherwise, the above function can take _any_ number of parameters. So perhaps declaring it with a void inside the parentheses may be a good choice. Just a minor nitpick.

**Comment by mcpcpc** [comment]
oof. fixed. ty! https://github.com/mcpcpc/kirc/commit/81f9dafa19157f4c0675875d25e7b83bcbc0d4c0
