### ISSUE TITLE
Aliases for some commands?

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#32]
Now, after all the IRC commands are supported directly, some of them are a bit of cumbersome. Like `PRIVMSG`, for example. 

Thus, would it be possible still to have some aliases? like `/m nick text goes here` would be actually understood by `kirc` as `/PRIVMSG nick :text goes here`?

**Comment by mcpcpc** [comment]
Yes!  Although, I would I would still like to keep aliased commands fairly limited.  

A `PRIVMSG` command alias _absolutely_ needs to exist. Some ideas on what that might look like...

/m/<channel|nick>/<message>

**Comment by 097115** [comment]
>  I would still like to keep aliased commands fairly limited

Agreed :)

> `/m/<channel|nick>/<message>`

Yeah, this looks acceptable (was thinking myself that treating the first two spaces as boundaries probably isn't a very good solution..)

**Comment by mcpcpc** [comment]
@097115 : note that i opted for a slightly more “modern” approach by using an `@` symbol. the _leader command character_ `/` is still required though.  in future iterations, i might decide to eliminate this one character so PRIVMSGs could simply sent as `@<channel|nick> <message>`.

**Comment by 097115** [comment]
@mcpcpc Seems to be working :) Thanks for such a speedy response! And yes, your idea about eliminating this one character sounds pretty nice.

**Comment by mcpcpc** [comment]
Decision made.   `/` character eliminated. ;)

See #34

**Comment by 097115** [comment]
@mcpcpc Have to say, very handy -- and very natural. Thanks :)
