### ISSUE TITLE
Additional highlighting for some events?

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#38]
Some events, like nick changes or leaving the channel seems not exactly distinguishable from the usual messaging. This, for example, is how parting the channel [looks like](https://i.imgur.com/HjjykdB.png). And this is the [nick change](https://i.imgur.com/Z4cL0w4.png).

May be some colouring could help to make them more obvious? And may be something like `->` for the nick change? What do you think?

**Comment by mcpcpc** [comment]
good suggestion.  definitely need to make these types of messages clearer.
