### ISSUE TITLE
VTEs: previous line of multi-line input cannot be deleted

### ISSUE THREAD

**Issue by mcpcpc** [mcpcpc/kirc#39]
## Background

This issue was first reported on _#kirc_ channel on Freenode and confirmed on multiple terminal emulators (see list below).  I was not able to reproduce over an SSH session or in other terminal emulators, so this **appears to be terminal emulator (TE) specific**. 

### confirmed impacted terminal emulators

*   [st](https://st.suckless.org/) - reported to dev@suckless.org
*   ~~[foot](https://codeberg.org/dnkl/foot)~~ - [reported](https://codeberg.org/dnkl/foot/issues/150) and PR initiated to implement `bw`.
*   [ate](https://github.com/andir/ate) - reported [upstream](https://github.com/andir/ate/issues/22), linked to [libvte](https://gitlab.gnome.org/GNOME/vte/-/issues/62).

### confirmed terminal emulators behaving "as expected"

*   [xterm](https://linux.die.net/man/1/xterm) (given that _reversewrap_ is enabled)
*   urxvt
*   wayst
*   most terminals using screen or tmux for terminal multiplexing

## To Reproduce

Read input from stdin (e.g. fgets, read, getline) and type more characters than the width of the terminal window. the text that is longer than window width is then printed as a new line, making the previous line uneditable.

```
#include <stdio.h
#include <stdlib.h>

int
main() {
    char a[1000];
    fgets(a, 1000, stdin);
    printf("string: %s\n", a);
    return 0;
}
```

## Further Discussion

*   [reddit](https://www.reddit.com/r/C_Programming/comments/j300kp/fgets_erase_previous_line_in_multiline_input/)

**Comment by mcpcpc** [comment]
Confirmed to be an issue upstream and was reported ~1yr ago (https://gitlab.gnome.org/GNOME/vte/-/issues/62).  Appears the best solution, for the time being, is to use a terminal multiplexer (such as `screen` or `tmux`) or `urxvt` which appropriately handle reverse linewrap.

**Comment by craigbarnes** [comment]
As noted in the foot issue, reading/writing to a terminal like this is never going to be portable. Even you you only target ECMA-48 compliant terminals.

I just threw together a quick [script] to see how many terminals in the ncurses terminfo database set the `bw` (a.k.a `auto_left_margin`) capability:

```
307/1339 terminals have 'bw' capability set
```

That leaves 1032 terminals where backspacing over the left margin won't work as you expect. In some cases it will even lock up the terminal completely until you issue an explicit move command.

Implicitly wrapping beyond the right margin (i.e. terminfo `am`/`auto_right_margin`) isn't entirely portable either, although ECMA-48 does at least specify the behaviour for that.

[script]: https://gitlab.com/craigbarnes/lua-terminfo-parser/-/blob/master/examples/has-bw.lua

**Comment by mcpcpc** [comment]
Hi Craig,

I appreciate the feedback.  Having followed the latest [foot](https://codeberg.org/dnkl/foot/issues/150) discussion, I would agree with your assessment. Although, I have yet to find a better fundamental solution, other than relying on a more “complete” library to handle cursor movement (which might sacrifice portability?).  

In terms of canonical vs raw modes, I attempted to stay in canonical mode in order to avoid creating a custom text editor or growing kirc significantly.  Hence, the many unorthodox practices, including switching in and out of raw/canonical modes (although this does solve the issue that other simple IRC clients, such as sic, have not resolved.

I pushed for this in foot as it seemed like a “good” idea at the time, without having reviewed ECMA-48. I appreciate the discussion though, which has made me rethink my approach.

**Comment by mcpcpc** [comment]
To summarize @craigbarnes and the discussions on multiple other threads, the default VTE terminfo flags are variable (from TE to TE) and, even with `bw` implemented and set, does not guarantee consistent behavior.  Trying to stay in canonical mode and pushing for upstream patching is not a viable solution to maintain portability and may need to be reconsidered.

**Comment by mcpcpc** [comment]
Based on the previous comments, the effort from the *foot* TE developers and added notes to the `README.md`, I think this issue can be closed for now.  Further `kirc` discussion on this matter should be focused on using non-canonical mode to create a real text editor.
