### ISSUE TITLE
*** stack smashing detected ***: terminated

### ISSUE THREAD

**Issue by LoLei** [mcpcpc/kirc#4]
`*** stack smashing detected ***: terminated` when joining a channel.

* kirc 0.0.4
* `$ ./kirc -n kirctest`
* OS: Arch Linux (linux 5.8.4-arch1-1)
* Terminal: Alacritty
* Shell: ZSH
* Log: [paste](https://hastebin.com/erohegowug.coffeescript)

![2020-08-28_13-40](https://user-images.githubusercontent.com/9076894/91557034-0209f680-e934-11ea-801a-e6a713e34fd3.png)

**Comment by mcpcpc** [comment]
Thank you for reporting this issue!  Well detailed.  

I am unable to reproduce with the current Makefile (although i am confident that i am currently not guarding against this issue).  What `gcc` flags are you passing?  

I imagine this not being a best practice, but for the short-term you could try passing `-fno-stack-protector -z execstack` to disable stack protection.

**Comment by LoLei** [comment]
I haven't used any additional flags other than what's in the Makefile. Your suggestion works though, can join channels now. Thanks!

Ah forgot to mention, in case it matters, using gcc version 10.2.0.

**Comment by mcpcpc** [comment]
commit https://github.com/mcpcpc/kirc/commit/bf1219105d3c2ddb4e37fa45ab1a80de0dda0bad should now address the need for any additional flags
