### ISSUE TITLE
Out-of-bound read

### ISSUE THREAD

**Issue by stensalweb** [mcpcpc/kirc#56]
**Describe the bug**
```
  Memory access error: reading from the outside of a memory block; abort!
  # Reading 1 bytes from 0xfff280eb will read undefined values.
  # 
  # The memory-block-to-be-read (start:0xfff280ec, size:512 bytes) is bound to 'usrin' at
  #    file:/tmp/kirc/kirc.c::618, 10
  # 
  #                               0xfff280ec           0xfff282eb
  #                               +--------------------------+
  #                         ......| memory-block-to-be-read  |
  #                               +--------------------------+
  #                            ^~~~~~~~~~
  #   the read starts at 0xfff280eb that is 1 bytes before the memory block start.
  # 
  # Stack trace (most recent call first) of the read.
  # [0]  file:/tmp/kirc/kirc.c::542, 9
  # [1]  file:/tmp/kirc/kirc.c::628, 17
  # [2]  [libc-start-main]
  https://cee.studio/explanation
```

**To Reproduce**
1. pull the latest code
2. the error message should be sufficient to decide if this is a bug. 
    if you want to reproduce it, you can  build it with our compiler https://www.cee.studio, it's free for open source developers.
3. run "DTS_LOG_FILE_NAME=/tmp/kirc.log ./kirc -c mupdf -n cee"
4. open /tmp/kirc.log to see this error. 

**Expected behavior**
kirc should not read from the outside of a memory block. 

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS:  Debian

**Comment by mcpcpc** [comment]
@stensalweb : I don’t have access to a console at the moment.  Would you mind checking if https://github.com/mcpcpc/kirc/pull/57 addresses error?

**Comment by stensalweb** [comment]
it's usable now. Thanks.
