### ISSUE TITLE
Clean up install section in Makefile

### ISSUE THREAD

**Issue by kdkasad** [mcpcpc/kirc#72]
Instead of using multiple commands to make directory structures, copy files, and set permissions, this patch uses the `install(1)` utility to do all 3 steps in one command.

```
The following changes since commit 80227542971a39eb2230250787546b891a02f93e:

  fix bug with server message printing (#71) (2020-10-20 20:35:04 -0400)

are available in the Git repository at:

  https://git.kasad.com/kirc.git master

for you to fetch changes up to 1efdc9a26a5891827f413e3394b55309843f4ec2:

  use install(1) instead of multiple commands (2020-10-21 00:42:23 -0700)

----------------------------------------------------------------
Kian Kasad (1):
      use install(1) instead of multiple commands

 Makefile | 9 +++------
 1 file changed, 3 insertions(+), 6 deletions(-)
```

**Comment by mcpcpc** [comment]
@kdkasad: I like this idea as it improves readability of the Makefile.  However, the one caveat is that `install` does not appear to be part of the standard POSIX utilities list (see [reference](https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html)).  Given that C99 POSIX compliance is fundamental to this project (to ensure maximum portability), I don't think it makes sense to adopt this change.  I am open to counter arguments or other suggestions though.

**Comment by kdkasad** [comment]
I didn't realize that. I'll create a different PR to combine the `mkdir` lines into one then, since that will also improve readability. I'll put that in this thread and update the title to fit.

**Comment by kdkasad** [comment]
Actually nevermind, it doesn't really help.
