### ISSUE TITLE
Notifications via external utilities

### ISSUE THREAD

**Issue by mcpcpc** [mcpcpc/kirc#73]
As suggested by @soliwilos on `#kisslinux` IRC, being able to pass notifications real-time to external applications is fundamental of many modern IRC clients. It would be nice if kirc could do so using built-in functionality or an explanation added on how to do so (using the support documentation).

**Target Notification Utilities**
- Herbe
- Wayherb

**Comment by mcpcpc** [comment]
First proposed external solution (requires output to be logged):

<script src="https://gist.github.com/mcpcpc/d40eb3ce2c01e49144ef7f75f7776c10.js"></script>

**Comment by soliwilos** [comment]
Thank you for looking into this feature for kirc.

I have a few thoughts, or questions regarding this first proposed external solution: 

If your channel(s) are slow and a message is written that causes a notification, you may be notification-spammed if the initiating message isn't replaced by other text in the last five lines of the log? Possibly also if kirc looses it's connection after having logged such a message?

Conversely, if your channel(s) are extremely busy it may happen that you won't receive notifications if the message is further back in the log before 5 seconds pass?

**Comment by mcpcpc** [comment]
> If your channel(s) are slow and a message is written that causes a notification, you may be notification-spammed if the initiating message isn't replaced by other text in the last five lines of the log?

Interestingly, this script does not seem to spam notifications.  I expected exactly as you described, but it only seems to send a new notification upon a change in the last 5 lines.  I am curious if this has something to do with the busybox implementation of tee? Either way, i think more testing is required.  Plus, we want the notification message to be informative (i.e privmsg sender nick).

>Conversely, if your channel(s) are extremely busy it may happen that you won't receive notifications if the message is further back in the log before 5 seconds pass?   

In my opinion, trying to catch every triggered event in the log will result in notification spam. The 5 second interval is intentional to keep the users attention and to draw them back to the terminal window for more information.  I don’t usually use a notification system in my personal setup, so it’s hard for me to speak to the optimal notification settings.

**Comment by soliwilos** [comment]
Have tested a slight variation of your script, to get notifications of mentions. I agree with information on sender nick, possibly also which channel (in the case of mentions, rather than private chat message).
```
#!/bin/sh
#
# checks log file for substring and sends notification and
# sends message to specified program.

main () {
    while true; do
        tail -fn5 "$1" | awk '/PRIVMSG #.*nick.*/ {
            system("wayherb \"kirc - new message\"")
            print "new message recieved!"
            exit
        }'
        sleep 5
    done
}

main "$1"
```

**Comment by mcpcpc** [comment]
I like it.  Simple enough that anyone can understand, customize or expand upon it. 

It’s officially part of the support documentation now: https://github.com/mcpcpc/kirc/blob/gh-pages/documentation.md

**Comment by mcpcpc** [comment]
@soliwilos : I think this shell script meets the intent of the original issue?  if so, I was thinking we could close this issue for now and re-open if there concerns later.

**Comment by soliwilos** [comment]
Yes, we can close this for now, thank you. I tinkered some more and got this, which now extracts the senders nick and includes it in the notification. It's sadly somewhat complex, but it works.
```
#!/bin/sh
#
# checks log file for substring, usually your own nick, and sends message to specified program.
# message notification includes the senders nick.

main () {
    while true; do
        tail -fn5 "$1" | awk '/PRIVMSG #.*nick.*/ {
            sub(/:/,""); sub(/!/," "); print "\x27" $1 " - new message" "\x27"
            exit
        }' | xargs wayherb
        sleep 5
    done
}

main "$1"
```
I also noticed that some nicknames seem to be cutoff at 16 characters? in the log output of kirc. I guess not many nicknames are that long, or longer, but I did encounter one such in the log output I was looking at.

**Comment by mcpcpc** [comment]
> I also noticed that some nicknames seem to be cutoff at 16 characters? in the log output of kirc. I guess not many nicknames are that long, or longer, but I did encounter one such in the log output I was looking at.

Search the log for “NICKLEN=”.  You will see Freenode limits the number of characters in a nick to 16.

**Comment by soliwilos** [comment]
Here is a script that relies on a named pipe instead of a normal txt file for kirc's log output, this means that logs will not be stored anywhere. Simply direct kirc's log output to the named pipe this script creates.
```
#!/bin/sh
#
# reads log data looking for substring, usually your own nick, 
# and sends message to specified program. The message notification 
# includes the senders nick.

pipe="$1"

[ -p "$pipe" ] || mkfifo -m 0600 "$pipe" || exit 1

main () {
    unset IFS
    while true; do
        if read -t 1 kirc; then
            printf %s "$kirc" | awk '/PRIVMSG #.*nick.*/ { 
            sub(/:/,""); sub(/!/," ");
            print "\x27" $1 " - new message" "\x27";
            exit }' | xargs -r wayherb &
        fi
    done < "$pipe" 4> "$pipe"
}

main "$pipe"
```
