### ISSUE TITLE
[feature] PKGBUILD for packaging on Arch Linux

### ISSUE THREAD

**Issue by kdkasad** [mcpcpc/kirc#8]
I created a PKGBUILD for packaging on Arch Linux and the AUR for kirc. It will build the latest git commit, so it requires no maintenance unless the build process changes.

```sh
pkgname=kirc-git
pkgver=0.0.6.r0.6a019c7
pkgrel=1
pkgdesc="KISS for IRC, an IRC client written in POSIX C99"
arch=(any)
url="https://github.com/mcpcpc/kirc"
license=('MIT')
makedepends=('git')
provides=("${pkgname%-git}")
conflicts=("${pkgname%-git}")
replaces=()
backup=()
options=()
install=
source=('kirc::git+https://github.com/mcpcpc/kirc.git')
md5sums=('SKIP')

pkgver() {
	cd "$srcdir/${pkgname%-git}"

	printf "%s" "$(git describe --tags --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

build() {
	cd "$srcdir/${pkgname%-git}"
	make
}

package() {
	cd "$srcdir/${pkgname%-git}"
	make DESTDIR="$pkgdir" install
}
```

I don't plan to use kirc (it's too simple for me), so I won't be maintaining an AUR package myself. That's why I submitted it as an issue instead.

**Comment by mcpcpc** [comment]
i like the idea.  I personally have never used Arch, but i will look into adding it to the AUR.

**Comment by kdkasad** [comment]
Actually, I'll do it for you. I forgot that you have to have the `makepkg` utility to create the right files. Plus, since there are no dependencies, it should be very easy to maintain.

**Comment by mcpcpc** [comment]
Awesome!  Thanks.
