### ISSUE TITLE
Channel name is not printed if cdef is a substring of the channel name

### ISSUE THREAD

**Issue by kdkasad** [mcpcpc/kirc#83]
**Describe the bug**
When receiving messages, channel is not printed if `cdef` is a substring of channel name.

**To Reproduce**
1. Join channel `#archlinux` (or any other channel)
2. Join channel `#archlinux-offtopic` (or any channel which contains the channel from step 1 in the name)
3. Set `#archlinux` as the default channel.
4. Recieve a message in `#archlinux-offtopic`
5. The channel name will not be printed next to the message, even though `#archlinux-offtopic` is not the default channel.

**Expected behavior**
The channel name (`#archlinux-offtopic` in the case of the test) should be printed before the message text.

**Actual behavior**
The channel name is not printed, because `strstr(3)` is used to check if the message is sent to the default channel, instead of `strcmp(3)`. This results in the channel name not being printed if `cdef` is *anywhere* in the channel name.

**Additional context**
I realized that this could be a problem while reading the code, then confirmed it using the test case above and Wireshark to ensure the channels were what I though they were, not what `kirc` printed.

**Comment by kdkasad** [comment]
Fixed downstream: https://git.kasad.com/kirc/commit/?id=4e4548ec6cd7cc66234cf82850f7990bb7eee35d

**Comment by mcpcpc** [comment]
fixed in https://github.com/mcpcpc/kirc/commit/640e4238dfc1eaa0157950cae8cf903872e1c926
