### ISSUE TITLE
With 0.2.1. printing a channel's info on join got a bit off..

### ISSUE THREAD

**Issue by 097115** [mcpcpc/kirc#92]
**Describe the bug**

With 0.2.1, now prepending `topic` and `names` information with the channel's name on join, lines wrapping got a bit mangled:

  - 0.2.0:

![020](https://i.imgur.com/iRIduCQ.png)

  - 0.2.1

![021](https://i.imgur.com/xwc7XjL.png)

**To Reproduce**
1. Run `kirc` in a relatively narrow window;
2. Join a channel;
3. Note that the first lines of `topic` and `names` commands now have the channel name prepended and their wrapping is incorrect.

**Expected behavior**

These new lines with channel names prepended should be wrapped in the same manner as all the other lines.

**Additional context**

Those `-W` and `-w` command line options were really nice, by the way :)

**Comment by mcpcpc** [comment]
should be fixed with #94.  getting late on my end, but will do some testing tomorrow to verify. 

Regarding the -w/-W arguments, i couldn’t really see a functional reason to keep them (other than aesthetics).  i might consider adding the ability to adjust the ratio of nick to message length though.

**Comment by 097115** [comment]
@mcpcpc Can confirm, 0.2.2 branch seems not to have this bug. Thanks! 

(You will close this after merge?)

**Comment by mcpcpc** [comment]
since this issue is linked to the PR, it will automagically close on merge.
